SurveyApp/Models/Survey.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SurveyApp.Models
{
    public class Survey
    {
        [Key]
        public int SurveyId { get; set; }


        [Required]
        public string Name { get; set; }

        [Required]
        public bool Published { get; set; }

        // Fk

        [Required]
        public string UserId { get; set; }

        [Required]
        public ApplicationUser User { get; set; }

        public virtual ICollection<Question> Questions { get; set; }

        public virtual ICollection<SurveyInstance> SurveyInstances { get; set; }

    }
}

SurveyApp/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SurveyApp.Data;
using SurveyApp.Models;

namespace SurveyApp.Controllers
{
    public class AnswersController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public AnswersController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Answers
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Answers.Include(a => a.Question);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Answers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _context.Answers
                .Include(a => a.Question)
                .FirstOrDefaultAsync(m => m.AnswerId == id);
            if (answer == null)
            {
                return NotFound();
            }

            return View(answer);
        }

        // GET: Answers/Create
        public IActionResult Create()
        {
            ViewData["QuestionId"] = new SelectList(_context.Questions, "QuestionId", "Content");
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AnswerId,Content,QuestionId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(answer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["QuestionId"] = new SelectList(_context.Questions, "QuestionId", "Content", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();

            var answer = await _context.Answers
                .Include(a => a.Question)
                    .ThenInclude(q => q.Survey)
                .SingleOrDefaultAsync(a => a.AnswerId == id);

            if (user.Id != answer.Question.Survey.UserId)
            {
                return NotFound();
            }


            if (answer == null)
            {
                return NotFound();
            }
           
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Answer Answer)
        {

            ModelState.Remove("QuestionId");

            if (ModelState.IsValid)
            {
                Answer answer = await _context.Answers.Include(a => a.Question).SingleOrDefaultAsync(a => a.AnswerId == id);

                try
                {

                    answer.Content = Answer.Content;

                    _context.Update(answer);
                    await _context.SaveChangesAsync();


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnswerExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Details", "Surveys", new { id = answer.Question.SurveyId });
            }
           
            return View(Answer);
        }

        // GET: Answers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _context.Answers
                .Include(a => a.Question)
                .FirstOrDefaultAsync(m => m.AnswerId == id);
            if (answer == null)
            {
                return NotFound();
            }

            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var answer = await _context.Answers.FindAsync(id);
            _context.Answers.Remove(answer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnswerExists(int id)
        {
            return _context.Answers.Any(e => e.AnswerId == id);
        }
    }
}

SurveyApp/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SurveyApp.Data;
using SurveyApp.Models;
using SurveyApp.Models.QandAViewModels;

namespace SurveyApp.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public QuestionsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }
        // GET: Questions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Questions.Include(q => q.Survey);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Questions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .Include(q => q.Survey)
                .FirstOrDefaultAsync(m => m.QuestionId == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // GET: Questions/Create
        public async Task<IActionResult> Create(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();

            Survey survey = await _context.Surveys.SingleOrDefaultAsync(s => s.SurveyId == id);

            CreateQuestionViewModel viewmodel = new CreateQuestionViewModel();

            viewmodel.Survey = survey;

            if (survey.UserId != user.Id)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(viewmodel);
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, CreateQuestionViewModel viewmodel)
        {
            ApplicationUser user = await GetCurrentUserAsync();

            viewmodel.Question.SurveyId = id;

            if (ModelState.IsValid)
            {
                _context.Add(viewmodel.Question);

                List<Answer> Answers = new List<Answer>();

                foreach (string answer in viewmodel.AnswerContents)
                {
                    Answer Answer = new Answer
                    {
                        Content = answer,
                        QuestionId = viewmodel.Question.QuestionId
                    };

                    Answers.Add(Answer);
                }

                foreach (Answer answer in Answers)
                {
                    _context.Add(answer);
                }




                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "Surveys", new { id = id });

            }
            return View("Index", "Home");

            // my new code
            //if (!_context.Questions.Any())
            //{
            //    var Questions = new Question[]
            //    {
            //        new Question {
            //            Content = "Electronics"
            //        }
            //    };

            //    foreach (Question i in Questions)
            //    {
            //        _context.Questions.Add(i);
            //    }
            //    _context.SaveChanges();



            //    if (!_context.Answers.Any())
            //    {
            //        var Answers = new Answer[]
            //        {
            //        new Answer {
            //            Content = "Kite",
            //            Question = _context.Questions.Single(t => t.Content == "Sporting Goods")
            //        }
            //        };

            //        foreach (Answer i in Answers)
            //        {
            //            _context.Answers.Add(i);
            //        }

            //        _context.SaveChanges();
            //    }

            //}
            //end my new code

            //if (ModelState.IsValid)
            //{
            //    _context.Add(question);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["SurveyId"] = new SelectList(_context.Surveys, "SurveyId", "Name", question.SurveyId);
            //return View(question);
        }

        // GET: Questions/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();

            var question = await _context.Questions
                .Include(q => q.Survey)
                .SingleOrDefaultAsync(q => q.QuestionId == id);

            if (user.Id != question.Survey.UserId)
            {
                return NotFound();
            }

            if (question == null)
            {
                return NotFound();
            }


            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Question Question)
        {
            ModelState.Remove("SurveyId");

            if (ModelState.IsValid)
            {
                    Question question = await _context.Questions.FindAsync(id);
                try
                {

                    question.Content = Question.Content;

                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Surveys", new { id = question.SurveyId });
            }
            return View(Question);
        }

        // GET: Questions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .Include(q => q.Survey)
                .FirstOrDefaultAsync(m => m.QuestionId == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
         

            //code to remove answerFK
            var question = await _context.Questions.Include(q => q.Answers).Include(q => q.Survey).SingleOrDefaultAsync(q => q.QuestionId == id);
            foreach (Answer answer in question.Answers)
            {
                _context.Remove(answer);
            }



            _context.Questions.Remove(question);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Surveys", new { id = question.Survey.SurveyId });
        }

        private bool QuestionExists(int id)
        {
            return _context.Questions.Any(e => e.QuestionId == id);
        }
    }
}

SurveyApp/Views/Surveys/Create.cshtml
@*Computer settings for appsettings.json*@
@*"Server=DESKTOP-VUH9TGJ\\SQLEXPRESS;database=SurveyApp;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"*@

@*Azure settings for appsettings.json*@
@*"DefaultConnection": "Server=tcp:bloopbloop.database.windows.net,1433;Initial Catalog=SurveyApp;Persist Security Info=False;User ID={Ds2q88};Password={Dejanst1988!!!};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"*@

@model SurveyApp.Models.Survey

@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="qnaContainer">
        <div class="surveyCreateContainer effect7">
            <form asp-action="Create">
                <h3 class="surveysPublished">Please name your survey</h3>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-info surveySurveyButton"  />
                    <a asp-action="Index" class="btn btn-info surveySurveyButton">Back</a>

                </div>
            </form>
        </div>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to Surveys</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SurveyApp/Views/Surveys/Delete.cshtml
@model SurveyApp.Models.Survey

@{
    ViewData["Title"] = "Delete";
}
<div class="qnaContainer">
    <div class="surveyCreateContainer effect7">
        <h3>Are you sure you want to delete this Survey?</h3>


        <h2 class="surveyDeleteName">
            @Html.DisplayFor(model => model.Name)
        </h2>


        <form asp-action="Delete">
            <input type="hidden" asp-for="SurveyId" />
            <input type="submit" value="Delete" class="btn btn-info surveySurveyButton" />
            <a asp-action="Index" class="btn btn-info surveySurveyButton">Back</a>
        </form>
    </div>
</div>

SurveyApp/Views/Surveys/Details.cshtml
@model SurveyApp.Models.Survey

@{
    ViewData["Title"] = "Details";
}
<div class="surveysPublished">
    <h2>Questions & Answers</h2>

    <p>
        <a asp-action="Create" asp-controller="Questions" asp-route-id="@Model.SurveyId" class="btn btn-info surveySurveyButton">Create New</a>
    </p>
</div>



<div class="qnaContainer">
    @foreach (var item in Model.Questions)
    {
        
    <div class="qnaQnaContainer effect7">
        <div class="qnaQuestionContainer">
            <div>
                @Html.DisplayFor(modelItem => item.Content)
            </div>
            <div>
                <a asp-action="Edit" asp-controller="Questions" asp-route-id="@item.QuestionId"><i class="fas fa-edit qnaQuestionEdit"></i></a>
                <a asp-action="Delete" asp-controller="Questions" asp-route-id="@item.QuestionId"><i class="fas fa-trash-alt qnaQuestionDelete"></i></a>
            </div>
        </div>


        <ol class="qnaOl">
            @foreach (var items in item.Answers)
            {

                <li class="qnaAnswers">
                    @Html.DisplayFor(modelItem => items.Content)


                    <a asp-action="Edit" asp-controller="Answers" asp-route-id="@items.AnswerId"><i class="fas fa-edit qnaAnswerEdit"></i></a>
                </li>
            }
        </ol>
    </div>
    }
</div>

SurveyApp/Views/Surveys/Edit.cshtml
@model SurveyApp.Models.Survey

@{
    ViewData["Title"] = "Edit";
}



<div class="qnaContainer">
    <div class="surveyCreateContainer effect7">
<h3 class=" surveysPublished">Edit your survey name</h3>
        <form asp-controller="Surveys" asp-action="Edit" asp-route-id="@Model.SurveyId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-info surveySurveyButton" />
    <a asp-action="Index" class="btn btn-info surveySurveyButton">Back</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SurveyApp/Views/Surveys/Index.cshtml
@model IEnumerable<SurveyApp.Models.Survey>

@{
    ViewData["Title"] = "Index";
}



<h2 class="surveysTitle">Surveys</h2>

<p class="createSurveyButton">
    <a class="btn btn-info surveySurveyButton"  asp-action="Create">Create New</a>
</p>
<div class="table">

    
@foreach (var item in Model) {
        <div class="surveysContent effect7">
            <div class="surveysHeader">
                @Html.DisplayFor(modelItem => item.Name)
            </div>
            <div>
                @*@Html.DisplayFor(modelItem => item.User.FullName)*@
            </div>
            <div>

                @if (item.Published == false)
                {
                    
                        @*@Html.DisplayFor(modelItem => item.Published)*@
                        @*<a asp-action="Publish" class="btn btn-info surveySurveyButton" asp-route-id="@item.SurveyId">Publish</a>*@
                        <form asp-controller="Surveys" asp-action="Publish" asp-route-id="@item.SurveyId" class="surveySurveyFormButton">
                            <button type="submit" class="btn btn-info surveyPublishButton">Publish</button>
                        </form>
                   
                    <a asp-action="Edit" class="btn btn-info surveySurveyButton" asp-route-id="@item.SurveyId">Edit</a>
                    <a asp-action="Details" class="btn btn-info surveySurveyButton" asp-route-id="@item.SurveyId">Q & A</a>
                    <a asp-action="Delete" class="btn btn-info surveySurveyButton" asp-route-id="@item.SurveyId">Delete</a>
                }
                else
                {

                    <a asp-action="Delete" class="btn btn-info surveySurveyButton" asp-route-id="@item.SurveyId">Delete</a>
                    <a asp-action="SurveyDetails" class="btn btn-info surveySurveyButton" asp-route-id="@item.SurveyId">Survey Results</a>
                }
            </div>
        </div>
}
</div>

SurveyApp/Views/Surveys/SurveyDetails.cshtml
@model SurveyApp.Models.SurveyDetailsViewModels.SruveyDetailsViewModel

@{
    ViewData["Title"] = "SurveyDetails";
}

<h2 class="resultsHeader">Survey Results For @Model.Survey.Name</h2>


<div class=" qnaContainer">
    @for (var i = 0; i < Model.Questions.Count; i++)
    {
        
        <input type="hidden" value="@Model.Questions[i].Content" id="question-@(i + 1)" class="question-data" />
        <div class=""></div>
        <div class="qnaQnaContainer effect7">
           
            <h4 class="qnaQuestionContainer no-top-margin">@Model.Questions[i].Content</h4>

            <ul class="ulHidden">
                @for (var j = 0; j < Model.Questions[i].Answers.Count; j++)
                {
                    <li>
                        <input type="hidden" value="@Model.Questions[i].Answers[j].Content--@Model.Questions[i].Answers[j].AnswerSurveyInstances.Count" class="answer-data" id="answer-@(j + 1)-q-@(i + 1)" />
                        @*<span>@Model.Questions[i].Answers[j].Content</span>
                        <span>:</span>
                        <span>@Model.Questions[i].Answers[j].AnswerSurveyInstances.Count</span>*@
                    </li>
                }

            </ul>
            <div class="chartContainerContainer">
                <div class="chartContainer">
                    <div Style="font-family: Corbel; font-size: small ;text-align:center " class="">
                        <div class=" chartSize">
                            <canvas class="answer-chart" id="myChart-@(i + 1)" style="padding: 0;margin: auto;display: block; "> </canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>